# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0y8TeuqGhDZ1pfv6tMXeR8cuDTSGISy

Write a Python program to print "Anything You find cool."
"""

print("hehe")

"""Q2 Add Numbers and Concatenate Strings  
2.1 Write a program to add two numbers and print the result.                                  
"""

a = 10
b = 12
a+b

"""2.2 Write a program to concatenate two strings and print the result."""

a = "Taran"
b = "deep"
a+b

"""2.3 Write a program to concatenate a string and a number and print the result."""

a = "Tarandeep"
b = 028
a+b

"""3.1 Write a Python program to check if a number is positive, negative, or zero
using an
if-else statement.
"""

a = 10
if a>0:
    print("positive")
elif a<0:
    print("negative")
else:
    print("zero")

"""3.2 Write a program to check if a given number is odd or even."""

a = 12
if a%2==0:
    print("even")
else:
    print("odd")

""" 4.1 Write a program to print numbers from 1 to 10 using a
for loop.
"""

for i in range(1,11):
  print(i)

"""4.2 Write a program to print numbers from 1 to 10 using a
while loop.
"""

i = 1
while i in range(1,11):
  print(i)
  i = i+1

"""4.3 Write a program to calculate the sum of numbers from 1 to 100 using a loop."""

total = 0
for i in range(1,101):
  total = total+i
print(total)

""" 5.1 Create a list of 5 numbers. Write a program to find the largest and smallest
numbers in the list.
"""

numbers = [1,2,3,4,5]
max = max(numbers)
min = min(numbers)
print(max)
print(min)

""" 5.2 Create a dictionary with at least 3 key-value pairs. Write a program to retrieve
the value of a given key.
"""

dictionary = {1: 'key',2: 'value',3: 'pairs'}
print(dictionary)

""" 5.3 Write a program to sort a list of numbers in ascending and descending order."""

numbers = [5,7,3,6,2,4,1]
numbers.sort()
print(numbers)
numbers.sort(reverse=True)
print(numbers)

""" 5.4 Write a program to merge two dictionaries into one."""

dictionary1 = {1: 'key',2: 'value',3: 'pairs'}
dictionary2 = {4: 'key',5: 'value',6: 'pairs'}
print(dictionary1|dictionary2)

""" 6.1 Write a program to count the number of vowels in a given string."""

string = "Tarandeep"
vowels = "aeiouAEIOU"
count = 0
for vowel in string:
  if vowel in vowels:
    count = count+1
print(count)

"""6.2 Write a program to reverse a string and print it."""

string = "Tarandeep"
reverse = string[::-1]
print(reverse)

""" 6.3 Write a program to check if a string is a palindrome."""

string = "level"
reverse = string[::-1]
if string == reverse:
  print("palindrome")
else:
  print("not palindrome")

"""7.1 Write a program to create a text file, write some text into it, and then read and
print the content.
"""

